### PR TITLE
Add zh_CN.lang

### PR DESCRIPTION
**Pull request by ItIsNotAPlayer**
Add Simplified Chinese translation.

### CODE REVIEW

**Comment by Eldeston** [comment]
Hello, I would like to note that there is a missing translation for `value.OUTLINES.2`. This can be ignored if it is intentional.

However, many options have been renamed recently such as `AUTO_GEN_NORM` to `NORMAL_GENERATION`. Please update to the latest en_US.lang format and include the language format version indicated in the comments here:
image

Please also note whenever the main en_US language format has been updated, the other language files will need updating as well if the version number has been updated.

**Comment by ItIsNotAPlayer** [comment]
The translation for`value.OUTLINES.2` is intentional.
I have updated the file to v1.0.1, but I'm not sure if I will update it on time in the future.

**Comment by Eldeston** [comment]
Hello thanks for updating. Please add your name in [this file](https://github.com/Eldeston/Super-Duper-Vanilla/blob/master/TRANSLATORS.md) as stated in [CONTRIBUTION.md](https://github.com/Eldeston/Super-Duper-Vanilla/blob/master/CONTRIBUTION.md#miscellaneous).

We would need a second person who also knows this language to review and confirm this file to be immediately merged.

**Comment by ItIsNotAPlayer** [comment]
Sorry, I has updated this file after a discussion with @NakiriRuri. She also knows Simplified Chinese and had translated a lot of shaders. It is a big update. Will you merge this file again?

**Pull request merged**
