### PR TITLE
Raw installer code (unconverted, passed testing)

### PR DESCRIPTION
**Pull request by steb-git**

### CODE REVIEW

**Review by steb-git — COMMENTED** [review]
I had to repull this again after converting it as an .exe for better portability. for now, i'll be pushing this in the meantime

**Comment by Eldeston** [comment]
I thought it's just a separate program?

**Comment by Eldeston** [comment]
Also just leave the installer only and delete the rest of the files since the test branch currently contains something important then I'll merge.

**Comment by steb-git** [comment]
I only pushed one file, which is the standalone installer, I don't know if i accidentally pushed some other files which is unintentional. Anyways should i pish this to master?

**Comment by Eldeston** [comment]
Not quite yet, also you did have other files included. Just remove then I'll merge this to testBtanch and make preparations.

Also write your username in CONTRIBUTOTS.md :P

**Comment by Eldeston** [comment]
*CONTRIBUTORS.md

I will merge the final product after some preparations.

**Comment by steb-git** [comment]
yeah sure, let me reopen this with the new files, for now i'll be closing this

**Pull request closed without merging**
